version: "2"
services:
  storage-ms:
    build: .
    ports:
      - "3001:3001"
    links:
      - storage-db
  storage-db:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "3307:3307"